api/urls.py
try:
    from django.conf.urls import *
except ImportError:  # django < 1.4
    from django.conf.urls.defaults import *

# place app url patterns here

from djangomonitcollector.users.models import User
from rest_framework import routers
from api.views import UserViewSet
from api import views


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^online-servers/$', views.OnlineServerList.as_view(), name="online-server-list"),
    url(r'^offline-servers/$', views.OfflineServerList.as_view(), name="offline-server-list"),
    url(r'^all-servers/$', views.ServerList.as_view(), name="server-list"),
    url(r'^server/(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$', views.ServerDetail.as_view(), name="server-detail"),
    url(r'^server/(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/alert$', views.ServerAlertList.as_view(), name="server-alert"),
    url(r'^alert/(?P<pk>[0-9]*)$', views.AlertDetail.as_view(), name="alert-detail"),
]

config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from django.views.generic.base import RedirectView
from rest_framework_swagger.views import get_swagger_view
from django.conf import settings  # import the settings file


favicon_view = RedirectView.as_view(
    url='/static/favicon/favicon.ico', permanent=True)
favicon_16_view = RedirectView.as_view(
    url='/static/favicon/favicon-16x16.png', permanent=True)
favicon_32_view = RedirectView.as_view(
    url='/static/favicon/favicon-32x32.png', permanent=True)
apple_touch_icon = RedirectView.as_view(
    url='/static/favicon/apple-touch-icon.png', permanent=True)
android_manifest = RedirectView.as_view(
    url='/static/favicon/manifest.json', permanent=True)
safari_pinned_tab = RedirectView.as_view(
    url='/static/favicon/safari-pinned-tab.svg', permanent=True)

app_name = settings.APPNAME
api_version = settings.APIVERSION


schema_view = get_swagger_view(
    title="{} API v{}".format(app_name, api_version))

urlpatterns = [


    # Restful API
    url(r'^v1/$', schema_view, name="kairos_api"),
    url(r'^v1/', include("api.urls")),

    # Favicons
    url(r'^favicon\.ico$', favicon_view),
    url(r'^favicon\-16x16\.png$', favicon_16_view),
    url(r'^favicon\-32x32\.png$', favicon_32_view),
    url(r'^apple\-touch\-icon\.png$', apple_touch_icon),
    url(r'^manifest\.json$', android_manifest),
    url(r'^safari\-pinned\-tab\.svg$', safari_pinned_tab),


    # Home
    url(r'^$', 'djangomonitcollector.ui.views.dashboard', name="home"),

    # About
    url(r'^about/$',
        TemplateView.as_view(template_name='pages/about.html'), name="about"),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/',
        include("djangomonitcollector.users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    # DataCollector
    url(r'^dc/', include("djangomonitcollector.datacollector.urls",
                         namespace="datacollector")),

    # UI
    url(r'^ui/', include("djangomonitcollector.ui.urls", namespace="ui")),

    # Notification
    url(r'^notification/',
        include("djangomonitcollector.notificationsystem.urls", namespace="n")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request),
        url(r'^403/$', default_views.permission_denied),
        url(r'^404/$', default_views.page_not_found),
        url(r'^500/$', default_views.server_error),
    ]

djangomonitcollector/datacollector/urls.py
from django.conf.urls import url

from djangomonitcollector.datacollector.views import OrganisationListView,\
    OrganisationCreateView,\
    OrganisationUpdateView,\
    collector,\
    list_servers,\
    delete_server

urlpatterns = [

    url(r'^organisations/$',
        OrganisationListView.as_view(),
        name='organisations'),

    url(r'^new_organisation/$',
        OrganisationCreateView.as_view(),
        name='new_organisation'),

    url(r'^update_organisation/(?P<pk>.+)/$',
        OrganisationUpdateView.as_view(),
        name='update_organisation'),

    url(r'^delete/([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        delete_server,
        name='delete_server'),
    url(
        r'^collector/(?P<collector_key>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        collector,
        name='collector'
    ),
    url(
        r'^collector/(?P<collector_key>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/(?P<host_group>.+)/$',
        collector,
        name='collector_with_host_group'
    ),
    url(
        r'^get_servers/$',
        list_servers,
        name='list_servers'
    ),
]

djangomonitcollector/notificationsystem/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^notificationtype/get_plugin_form/$',
        view=views.get_notification_plugin_form,
        name='get_plugin_form'
    ),
    url(
        regex=r'^notificationtype/create/$',
        view=views.NotificationTypeCreate.as_view(),
        name='notificationtype_create'
    ),
    url(
        regex=r'^notificationtype/show/(?P<pk>[0-9a-z]+)/$',
        view=views.NotificationTypeView.as_view(),
        name='notificationtype_view'
    ),
    url(
        regex=r'^notificationtype/mute/(?P<pk>[0-9a-z]+)/$',
        view=views.notificationtype_mute_all,
        name='notification_mute_all'
    ),
    url(
        regex=r'^notificationtype/update/(?P<pk>[0-9a-z]+)/$',
        view=views.NotificationTypeUpdate.as_view(),
        name='notificationtype_update'
    ),
    url(
        regex=r'^notificationtype/toggle/(?P<pk>[0-9a-z]+)/$',
        view=views.notificationtypeactivation,
        name='notificationtype_activation'
    ),
    url(
        regex=r'^notificationtype/delete/(?P<pk>[0-9a-z]+)/$',
        view=views.NotificationTypeDelete.as_view(),
        name='notificationtype_delete'
    ),
    url(
        regex=r'^notificationtype/list/$',
        view=views.NotificationTypeListView.as_view(),
        name='notificationtype_list'
    ),
    url(
        regex=r'^event/get_row/$',
        view=views.get_event_row,
        name='get_event_row'
    ),
    url(
        regex=r'^event/get/$',
        view=views.get_event_details,
        name='get_event_details'
    ),
    url(
        regex=r'^notification/get/$',
        view=views.get_notification_details,
        name='get_notification_details'
    ),
    url(
        regex=r'^postcomment/$',
        view=views.postcomment,
        name='postcomment'
    ),

]

djangomonitcollector/ui/urls.py
from . import views
from django.conf.urls import url


urlpatterns = [

    url(
        regex=r'^$',
        view=views.dashboard,
        name='dashboard'
    ),
    url(
        regex=r'^notifications/$',
        view=views.notifications,
        name='notifications'
    ),

    url(
        regex=r'^dashboard/$',
        view=views.dashboard,
        name='dashboard'
    ),
    url(
        regex=r'^server/update/(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        view=views.ServerUpdateView.as_view(),
        name='server_update'
    ),
    url(
        regex=r'^server/delete/(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        view=views.ServerDeleteView.as_view(),
        name='server_delete'
    ),
    url(
        regex=r'^server/show/(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        view=views.ServerShowView.as_view(),
        name='server_show'
    ),
    url(
        regex=r'^server/kpis/(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        view=views.serverkpis,
        name='server_kpis'
    ),
    url(
        regex=r'^server/(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/alerts/list/$',
        view=views.EventListView.as_view(),
        name='server_alerts'
    ),
    url(
        regex=r'^server/(?P<server_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        view=views.server,
        name='server'
    ),
    url(
        regex=r'^server/(?P<server_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/process/(?P<process_name>[^/]+)/$',
        view=views.process,
        name='process'
    ),
    url(
        regex=r'^server/(?P<server_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/filesystem/(?P<filesystem_id>[^/]+)/$',
        view=views.filesystem,
        name='filesystem'
    ),
    url(
        regex=r'^server/(?P<server_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/network/(?P<network_name>[^/]+)/$',
        view=views.network,
        name='network'
    ),
    url(
        regex=r'^confirm_delete/(?P<server_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        view=views.confirm_delete,
        name='confirm_delete'
    ),
    url(
        regex=r'^delete_server/(?P<server_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        view=views.delete_server,
        name='delete_server'
    ),
    url(
        regex=r'ackevent/$',
        view=views.ack_event,
        name='ack_event'
    ),
    url(
        regex=r'^load_dashboard_table/$',
        view=views.load_dashboard_table,
        name='load_dashboard_table'
    ),
    url(
        regex=r'settings/(?P<pk>.*)/$$',
        view=views.SettingsUpdateView.as_view(),
        name='settings_update'
    ),
    url(
        regex=r'intellievent/$',
        view=views.IntelliEvent.as_view(),
        name='intellievent'
    ),
    url(
        regex=r'intellievent2/$',
        view=views.intellievent_list,
        name='intellievent_2'
    ),
    url(
        regex=r'update_hgs/$',
        view=views.update_user_hgs,
        name='update_hgs'
    ),
    url(
        regex=r'set_stats_period/$',
        view=views.set_stats_period,
        name='set_stats_period'
    ),
    url(
        regex=r'last_week_events/$',
        view=views.get_weeks_events,
        name='last_week_events'
    ),
    url(
        regex=r'today_events/$',
        view=views._get_todays_events,
        name='today_events'
    ),

]

djangomonitcollector/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [

    url(
        regex=r'del_api_key/$',
        view=views.delete_api_key,
        name='delete_api_key'
    ),
    url(
        regex=r'new_api_key/$',
        view=views.new_api_key,
        name='new_api_key'
    ),
    url(
        regex=r'update_user_settings/$',
        view=views.update_user_settings,
        name='update_user_settings'
    ),
    url(
        r'^create/$',
        views.UserCreate.as_view(),
        name='create'
    ),
    url(
        regex=r'newck/$',
        view=views.new_collector_key,
        name='new_collector_key'
    ),
    url(
        regex=r'delck/$',
        view=views.delete_collector_key,
        name='delete_collector_key'
    ),

    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='index'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^update/(?P<pk>.+)/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),

    url(r'^delete/(?P<username>[\w.@+-]+)/$',
        views.UserDeleteView.as_view(), name='delete'),
    url(r'^update_password/(?P<pk>.+)/$',
        views.UpdatePasswordForUser, name='update_password'),
    url(r'^update_password/$', views.UpdatePassword,
        name='update_password_cu'),



]

djangomonitcollector/datacollector/models/File.py
from django.db import models

from service import Service
from utils import get_value, decode_status


class File(Service):
    server = models.ForeignKey('Server')

    @classmethod
    def update(cls, xmldoc, server, service):
        filename = get_value(service, "", "", "name")
        file, created = cls.objects.get_or_create(server=server, name=filename)
        file.name = filename
        file.status = decode_status(int(get_value(service, "status", "")))
        file.status_hint = get_value(service, "status_hint", "")
        file.monitor = get_value(service, "monitor", "")
        file.monitormode = get_value(service, "monitormode", "")
        file.pendingaction = get_value(service, "pendingaction", "")
        file.save()

djangomonitcollector/datacollector/models/Platform.py
from django.db import models

from utils import get_value


class Platform(models.Model):
    server = models.OneToOneField('Server')
    name = models.TextField(null=True)
    release = models.TextField(null=True)
    version = models.TextField(null=True)
    machine = models.TextField(null=True)
    cpu = models.IntegerField(null=True)
    memory = models.IntegerField(null=True)
    swap = models.IntegerField(null=True)

    @classmethod
    def update(cls, xmldoc, server):
        platform, created = Platform.objects.get_or_create(server=server)
        platform.name = get_value(xmldoc, "platform", "name")
        platform.release = get_value(xmldoc, "platform", "release")
        platform.version = get_value(xmldoc, "platform", "version")
        platform.machine = get_value(xmldoc, "platform", "machine")
        platform.cpu = get_value(xmldoc, "platform", "cpu")
        platform.memory = get_value(xmldoc, "platform", "memory")
        platform.swap = get_value(xmldoc, "platform", "swap")
        platform.save()

djangomonitcollector/datacollector/models/Server.py
from django.db import models

from process import Process
from system import System
from net import Net
from filesystem import FileSystem
from platform import Platform
from file import File
from program import Program
from utils import remove_old_services, get_value
from xml.dom import minidom


class Server(models.Model):
    monit_id = models.CharField(max_length=32, unique=True)
    monit_version = models.TextField(null=True)
    localhostname = models.TextField(null=True)
    uptime = models.IntegerField(null=True)
    address = models.TextField(null=True)

    @classmethod
    def update(cls, xmldoc, monit_id):
        reporting_services = []
        server, created = cls.objects.get_or_create(monit_id=monit_id)
        server.monit_version = xmldoc.getElementsByTagName('monit')[0].attributes["version"].value
        server.localhostname = get_value(xmldoc, "localhostname", "")
        server.uptime = get_value(xmldoc, "server", "uptime")
        server.address = get_value(xmldoc, "server", "address")
        server.save()
        Platform.update(xmldoc, server)
        for service in xmldoc.getElementsByTagName('services')[0].getElementsByTagName('service'):
            service_type = get_value(service, "type", "")
            service_name = get_value(service, "", "", "name")
            reporting_services.append(service_name)
            print "{0} {1}".format(service_name, service_type)
            if service_type == '3':  # Process
                Process.update(xmldoc, server, service)
            elif service_type == '5':  # System Analysis
                System.update(xmldoc, server, service)
            elif service_type == '8':  # Network Card
                Net.update(xmldoc, server, service)
            elif service_type == '0':  # Filesystem
                FileSystem.update(xmldoc, server, service)
            elif service_type == '2':  # File
                File.update(xmldoc, server, service)
            elif service_type == '7':  # Url
                Program.update(xmldoc, server, service)
            else:
                Process.update(xmldoc, server, service)
        remove_old_services(server, reporting_services)

def collect_data(xml_str):
    # only ready data if it has a monit id
    try:
        xmldoc = minidom.parseString(xml_str)
        monit_id = xmldoc.getElementsByTagName('monit')[0].attributes["id"].value
    except:
        return False, "Problem parsing the xml document"
    try:
        Server.update(xmldoc, monit_id)
    except:
        return False, "Error While updatingh the server instance"
    return True, "Server instance Updated"

djangomonitcollector/datacollector/models/Service.py
from django.db import models


# Service
class Service(models.Model):
    # not unique since there could be multiple server with service 'nginx', etc.
    name = models.TextField()
    status = models.TextField(null=True)
    status_hint = models.IntegerField(null=True)
    monitor = models.IntegerField(null=True)
    monitor_mode = models.IntegerField(null=True)
    pending_action = models.IntegerField(null=True)

djangomonitcollector/templates/ui/_events.html
{% load extra_tags %}
<div class="scrollable" style="max-height: 200px; overflow-y: hidden;">
    {% for monit_event in events %}
    <div class="row" style="border-top: 1px solid rgba(255,255,255,.02);">
        <div class="row col-md-12">
            <div class="col-md-4">
                <div class="p-5" >
                    <b><span class="label label-{{ monit_event.event_state|event_state_to_style }}">{{ monit_event.event_state|event_state_to_string }}</span></b>
                    <b><span style="font-size:1em">{{ monit_event.event_id|event_status_to_string|title }}</span></b>
                </div>
            </div>
            <div class="col-md-4 p-5"><b>Server : </b>{{ monit_event.server.localhostname }}</div>
            <div class="col-md-4 p-5">

                <span class="pull-right btn btn-xs c-lime" data-toggle="tooltip" data-placement="top" title="{{ monit_event.event_time}}"><i class="zmdi zmdi-time"></i> {{ monit_event.event_time|time_diff|format_timedelta }}</span>
            </div>
        </div>
        <div class="row col-md-12">
            <p class="m-l-25 m-b-xs m-5 c-bluegray">
                {{ monit_event.event_message }}
            </p>
        </div>
    </div>
    {% endfor %}
</div>
<script language="javascript">
$(document).ready(function () {

 $(".scrollable").mCustomScrollbar();
})
 </script>

djangomonitcollector/templates/ui/_page_header.html
<div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-sm-4">
            <h2></h2>
            <ol class="breadcrumb">
                <li>
                    <a href="index.html">This is</a>
                </li>
                <li class="active">
                    <strong>Breadcrumb</strong>
                </li>
            </ol>
        </div>
        <div class="col-sm-8">
            <div class="title-action">
                <a href="" class="btn btn-primary">This is action area</a>
            </div>
        </div>
    </div>

djangomonitcollector/templates/ui/_topnavbar.html
{% load  i18n %}
{% load extra_tags %}

<div class="row border-bottom">
    <nav class="navbar navbar-fixed-top" role="navigation" style="margin-bottom: 0">
        {% if request.user.is_authenticated %}
        <div class="navbar-header">
            <a id="collapsemenu" class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
        </div>
        {% endif %}


        <ul class="nav navbar-top-links navbar-right">

            {% if request.user.is_authenticated %}
                {% if not request.user.is_superuser %}
                        <li >
                            <a class="nav-link count-info dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell-o"></i><span id="notification_count"></span></a>
                                <ul class="dropdown-menu dropdown-messages">

                                    <li>
                                        <div class="text-center link-block">
                                            <a  href="{% url 'ui:intellievent' %}">
                                                <i class="fa fa-bell"></i> <strong>View All Alerts</strong>
                                            </a>
                                        </div>
                                    </li>
                                </ul>
                        </li>
                        <li >
                            |
                        </li>
                    {% if  request.user.organisation.server_set|get_server_len > 0 %}
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                                aria-expanded="false"><i class="fa fa-server"></i> Servers / Instances <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    {% for server in request.user.organisation.server_set.all %}
                                        <li><a href="{% url 'ui:server' server.id %}">{{ server.localhostname }}</a></li>
                                    {% endfor %}
                                </ul>
                            </li>
                    {% endif %}

                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                                aria-expanded="false"><i class="fa fa-bell"></i>{% trans "Notifications Center" %}<span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="{% url 'n:notificationtype_list' %}">{% trans "Manage Notifications" %}</a></li>
                                    <li><a href="{% url 'n:notificationtype_create' %}">{% trans "New Notification" %}</a></li>
                                </ul>
                            </li>

                    {% if request.user.organisation_manager %}
                            <li >
                                <a class="nav-link"
                                href="{% url 'ui:settings_update' request.user.organisation.settings.id %}"><i class="fa fa-wrench"></i>{% trans "Settings" %}</a>
                            </li>
                    {% endif %}

                {% endif %}
                        <li >
                        <a class="nav-link"
                            href="{% url 'users:detail' request.user.username %}"> <span class="text-navy" ><i class="fa fa-user"></i> {{ request.user|title }}</span></a>
                        </li>
                        <li >
                            <a class="nav-link" href="{% url 'account_logout' %}"><span class="text-danger" ><i class="fa fa-sign-out"></i> {% trans "Logout" %}</span></a>
                        </li>
            {% else %}
                        <li >
                            <a id="sign-up-link" class="nav-link"
                            href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
                        </li>
                        <li >
                            <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Log In" %}</a>
                        </li>
            {% endif %}

                </ul>
            </nav>
        </div>

djangomonitcollector/templates/ui/_topnavbar2.html
{% load  i18n %}
{% load extra_tags %}
{% if request.user.is_authenticated %}
  {% if not request.user.is_superuser %}
    <li class="dropdown nav-link" >
      <a data-toggle="dropdown" href="">
        <i class="him-icon zmdi zmdi-notifications"></i>
        <i class="him-counts m-r-10" id="notification_count" style="display:none"></i><span class="him-label hidden-xs"></span>
      </a>
      <div class="dropdown-menu dropdown-menu-lg pull-right">
        <div class="list-group list-group-light him-notification">
          <div class="lg-header">
            Notifications
            <ul class="actions">
              <li class="dropdown">
                <a href="" data-ma-action="clear-notification">
                  <i class="zmdi zmdi-check-all"></i>
                </a>
              </li>
            </ul>
          </div>
          <div class="lg-body scrollable" style="overflow: hidden;">
            {% for monit_event in organisation_events %}
              {% include "ui/includes/_event_notification_row.html" %}
            {% endfor %}
          </div>
         <!-- <a class="view-more view-more-light" href="{% url 'ui:intellievent' %}">{% trans "View all" %}</a>   -->
         <a class="view-more view-more-light c-gray" href="{% url 'ui:intellievent_2' %}"><strong>{% trans "View all" %}</strong></a>

        </div>
      </div>
    </li>
    {% if  request.user.organisation.server_set|get_server_len > 0 %}
    <li class="dropdown">
      <a class="dropdown-toggle " data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="him-icon zmdi zmdi-storage"></i><span class="him-label hidden-xs">{% trans 'Servers / Instances' %}</span><span class="caret"></span></a>
      <ul class="dropdown-menu">
        {% for server in request.user.organisation.server_set.all %}
            <li><a href="{% url 'ui:server' server.id %}"> {{ server.localhostname }}</a></li>
        {% endfor %}
      </ul>
    </li>
      {% endif %}
    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
        aria-expanded="false"><i class="him-icon zmdi zmdi-notifications-none"></i><span class="him-label hidden-xs">{% trans "Notifications Center" %}</span><span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="{% url 'n:notificationtype_list' %}"> {% trans "Manage Notifications" %}</a></li>
          <li><a href="{% url 'n:notificationtype_create' %}"> {% trans "New Notification" %}</a></li>
        </ul>
    </li>
    <li class="nav-link">
      <a href="{% url 'account_logout' %}" class="c-red"><i class="him-icon zmdi zmdi-power"></i><span class="him-label hidden-xs">{% trans 'Logout' %}</span></a>
    </li>
        {% endif %}
      {% else %}
    <li class="nav-link">
      <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}#login"><i class="fa fa-sign-in fa-lg"></i><span class="him-label hidden-xs">{% trans "Log In" %}</span></a>
    </li>
        {% endif %}

djangomonitcollector/templates/ui/error.html
{% extends "base.html" %}

{% block jumbotron %}
<h1 style="font-size:50px;">
	Error
</h1>
{% endblock %}


{% block content %}
    Timeout after {{time_out}} seconds for connection to server with url <b>http://{{monit_user}}:(pw_not_shown)@{{ip_address}}:{{monit_port}}/{{process_name}}</b>. Please make sure the correct 
    user, password and port are used and that the request is not blocked by the firewall. If the url is wrong please open an issue on 
    <a href="https://github.com/nleng/djangomonitcollector" target='_blank'>github.</a>
{% endblock %}