api/urls.py
try:
    from django.conf.urls import *
except ImportError:  # django < 1.4
    from django.conf.urls.defaults import *

# place app url patterns here

from djangomonitcollector.users.models import User
from rest_framework import routers
from api.views import UserViewSet
from api import views


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^online-servers/$', views.OnlineServerList.as_view(), name="online-server-list"),
    url(r'^offline-servers/$', views.OfflineServerList.as_view(), name="offline-server-list"),
    url(r'^all-servers/$', views.ServerList.as_view(), name="server-list"),
    url(r'^server/(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$', views.ServerDetail.as_view(), name="server-detail"),
    url(r'^server/(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/alert$', views.ServerAlertList.as_view(), name="server-alert"),
    url(r'^alert/(?P<pk>[0-9]*)$', views.AlertDetail.as_view(), name="alert-detail"),
]

config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from django.views.generic.base import RedirectView
from rest_framework_swagger.views import get_swagger_view
from django.conf import settings  # import the settings file


favicon_view = RedirectView.as_view(
    url='/static/favicon/favicon.ico', permanent=True)
favicon_16_view = RedirectView.as_view(
    url='/static/favicon/favicon-16x16.png', permanent=True)
favicon_32_view = RedirectView.as_view(
    url='/static/favicon/favicon-32x32.png', permanent=True)
apple_touch_icon = RedirectView.as_view(
    url='/static/favicon/apple-touch-icon.png', permanent=True)
android_manifest = RedirectView.as_view(
    url='/static/favicon/manifest.json', permanent=True)
safari_pinned_tab = RedirectView.as_view(
    url='/static/favicon/safari-pinned-tab.svg', permanent=True)

app_name = settings.APPNAME
api_version = settings.APIVERSION


schema_view = get_swagger_view(
    title="{} API v{}".format(app_name, api_version))

urlpatterns = [


    # Restful API
    url(r'^v1/$', schema_view, name="kairos_api"),
    url(r'^v1/', include("api.urls")),

    # Favicons
    url(r'^favicon\.ico$', favicon_view),
    url(r'^favicon\-16x16\.png$', favicon_16_view),
    url(r'^favicon\-32x32\.png$', favicon_32_view),
    url(r'^apple\-touch\-icon\.png$', apple_touch_icon),
    url(r'^manifest\.json$', android_manifest),
    url(r'^safari\-pinned\-tab\.svg$', safari_pinned_tab),


    # Home
    url(r'^$', 'djangomonitcollector.ui.views.dashboard', name="home"),

    # About
    url(r'^about/$',
        TemplateView.as_view(template_name='pages/about.html'), name="about"),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/',
        include("djangomonitcollector.users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    # DataCollector
    url(r'^dc/', include("djangomonitcollector.datacollector.urls",
                         namespace="datacollector")),

    # UI
    url(r'^ui/', include("djangomonitcollector.ui.urls", namespace="ui")),

    # Notification
    url(r'^notification/',
        include("djangomonitcollector.notificationsystem.urls", namespace="n")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request),
        url(r'^403/$', default_views.permission_denied),
        url(r'^404/$', default_views.page_not_found),
        url(r'^500/$', default_views.server_error),
    ]

djangomonitcollector/datacollector/urls.py
from django.conf.urls import url

from djangomonitcollector.datacollector.views import OrganisationListView,\
    OrganisationCreateView,\
    OrganisationUpdateView,\
    collector,\
    list_servers,\
    delete_server

urlpatterns = [

    url(r'^organisations/$',
        OrganisationListView.as_view(),
        name='organisations'),

    url(r'^new_organisation/$',
        OrganisationCreateView.as_view(),
        name='new_organisation'),

    url(r'^update_organisation/(?P<pk>.+)/$',
        OrganisationUpdateView.as_view(),
        name='update_organisation'),

    url(r'^delete/([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        delete_server,
        name='delete_server'),
    url(
        r'^collector/(?P<collector_key>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        collector,
        name='collector'
    ),
    url(
        r'^collector/(?P<collector_key>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/(?P<host_group>.+)/$',
        collector,
        name='collector_with_host_group'
    ),
    url(
        r'^get_servers/$',
        list_servers,
        name='list_servers'
    ),
]

djangomonitcollector/ui/urls.py
from . import views
from django.conf.urls import url


urlpatterns = [

    url(
        regex=r'^$',
        view=views.dashboard,
        name='dashboard'
    ),
    url(
        regex=r'^notifications/$',
        view=views.notifications,
        name='notifications'
    ),

    url(
        regex=r'^dashboard/$',
        view=views.dashboard,
        name='dashboard'
    ),
    url(
        regex=r'^server/update/(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        view=views.ServerUpdateView.as_view(),
        name='server_update'
    ),
    url(
        regex=r'^server/delete/(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        view=views.ServerDeleteView.as_view(),
        name='server_delete'
    ),
    url(
        regex=r'^server/show/(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        view=views.ServerShowView.as_view(),
        name='server_show'
    ),
    url(
        regex=r'^server/kpis/(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        view=views.serverkpis,
        name='server_kpis'
    ),
    url(
        regex=r'^server/(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/alerts/list/$',
        view=views.EventListView.as_view(),
        name='server_alerts'
    ),
    url(
        regex=r'^server/(?P<server_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        view=views.server,
        name='server'
    ),
    url(
        regex=r'^server/(?P<server_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/process/(?P<process_name>[^/]+)/$',
        view=views.process,
        name='process'
    ),
    url(
        regex=r'^server/(?P<server_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/filesystem/(?P<filesystem_id>[^/]+)/$',
        view=views.filesystem,
        name='filesystem'
    ),
    url(
        regex=r'^server/(?P<server_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/network/(?P<network_name>[^/]+)/$',
        view=views.network,
        name='network'
    ),
    url(
        regex=r'^confirm_delete/(?P<server_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        view=views.confirm_delete,
        name='confirm_delete'
    ),
    url(
        regex=r'^delete_server/(?P<server_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        view=views.delete_server,
        name='delete_server'
    ),
    url(
        regex=r'ackevent/$',
        view=views.ack_event,
        name='ack_event'
    ),
    url(
        regex=r'^load_dashboard_table/$',
        view=views.load_dashboard_table,
        name='load_dashboard_table'
    ),
    url(
        regex=r'settings/(?P<pk>.*)/$$',
        view=views.SettingsUpdateView.as_view(),
        name='settings_update'
    ),
    url(
        regex=r'intellievent/$',
        view=views.IntelliEvent.as_view(),
        name='intellievent'
    ),
    url(
        regex=r'intellievent2/$',
        view=views.intellievent_list,
        name='intellievent_2'
    ),
    url(
        regex=r'update_hgs/$',
        view=views.update_user_hgs,
        name='update_hgs'
    ),
    url(
        regex=r'set_stats_period/$',
        view=views.set_stats_period,
        name='set_stats_period'
    ),
    url(
        regex=r'last_week_events/$',
        view=views.get_weeks_events,
        name='last_week_events'
    ),
    url(
        regex=r'today_events/$',
        view=views._get_todays_events,
        name='today_events'
    ),

]

djangomonitcollector/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [

    url(
        regex=r'del_api_key/$',
        view=views.delete_api_key,
        name='delete_api_key'
    ),
    url(
        regex=r'new_api_key/$',
        view=views.new_api_key,
        name='new_api_key'
    ),
    url(
        regex=r'update_user_settings/$',
        view=views.update_user_settings,
        name='update_user_settings'
    ),
    url(
        r'^create/$',
        views.UserCreate.as_view(),
        name='create'
    ),
    url(
        regex=r'newck/$',
        view=views.new_collector_key,
        name='new_collector_key'
    ),
    url(
        regex=r'delck/$',
        view=views.delete_collector_key,
        name='delete_collector_key'
    ),

    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='index'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^update/(?P<pk>.+)/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),

    url(r'^delete/(?P<username>[\w.@+-]+)/$',
        views.UserDeleteView.as_view(), name='delete'),
    url(r'^update_password/(?P<pk>.+)/$',
        views.UpdatePasswordForUser, name='update_password'),
    url(r'^update_password/$', views.UpdatePassword,
        name='update_password_cu'),



]

djangomonitcollector/datacollector/models/File.py
from django.db import models

from service import Service
from utils import get_value, decode_status


class File(Service):
    server = models.ForeignKey('Server')

    @classmethod
    def update(cls, xmldoc, server, service):
        filename = get_value(service, "", "", "name")
        file, created = cls.objects.get_or_create(server=server, name=filename)
        file.name = filename
        file.status = decode_status(int(get_value(service, "status", "")))
        file.status_hint = get_value(service, "status_hint", "")
        file.monitor = get_value(service, "monitor", "")
        file.monitormode = get_value(service, "monitormode", "")
        file.pendingaction = get_value(service, "pendingaction", "")
        file.save()

djangomonitcollector/datacollector/models/FileSystem.py
from django.db import models

from service import Service
from utils import get_value, decode_status, json_list_append


class FileSystem(Service):
    server = models.ForeignKey('Server')
    date_last = models.PositiveIntegerField(null=True)
    file_system = models.TextField(null=True)
    mode = models.TextField(null=True)
    flags = models.IntegerField(null=True)

    blocks_percent = models.TextField(null=True)
    blocks_percent_last = models.FloatField(null=True)
    blocks_usage = models.TextField(null=True)
    blocks_usage_last = models.FloatField(null=True)
    blocks_total = models.TextField(null=True)

    inode_percent = models.TextField(null=True)
    inode_percent_last = models.FloatField(null=True)
    inode_usage = models.TextField(null=True)
    inode_usage_last = models.IntegerField(null=True)
    inode_total = models.TextField(null=True)

    @classmethod
    def update(cls, xmldoc, server, service):
        fs_name = get_value(service, "", "", "name")
        fs_name.replace('_', '')
        filesystem, created = cls.objects.get_or_create(server=server, name=fs_name)
        filesystem.name = fs_name
        filesystem.status = decode_status(int(get_value(service, "status", "")))
        filesystem.status_hint = get_value(service, "status_hint", "")
        filesystem.monitor = get_value(service, "monitor", "")
        filesystem.monitormode = get_value(service, "monitormode", "")
        filesystem.pendingaction = get_value(service, "pendingaction", "")

        # blocks
        percent_last = get_value(service, "block", "percent")
        if percent_last == "none":
            percent_last = "0.0"
        filesystem.blocks_percent_last = float(percent_last)
        filesystem.blocks_percent = json_list_append(filesystem.blocks_percent, filesystem.blocks_percent_last)

        # inode
        percent_last = get_value(service, "inode", "percent")
        if percent_last == "none":
            percent_last = "0.0"
        filesystem.inode_percent_last = float(percent_last)
        filesystem.inode_percent = json_list_append(filesystem.inode_percent, filesystem.inode_percent_last)

        filesystem.save()

djangomonitcollector/datacollector/models/Net.py
from django.db import models

from service import Service
from utils import get_value, decode_status, get_string, get_int


# type = 8
class Net(Service):
    server = models.ForeignKey('Server')
    date_last = models.PositiveIntegerField(null=True)
    state = models.IntegerField(null=True)
    speed = models.IntegerField(null=True)
    duplex = models.IntegerField(null=True)

    download_packet = models.IntegerField(null=True)
    download_packet_sum = models.IntegerField(null=True)
    download_bytes = models.IntegerField(null=True)
    download_bytes_sum = models.IntegerField(null=True)
    download_errors = models.IntegerField(null=True)
    download_errors_sum = models.IntegerField(null=True)

    upload_packet = models.IntegerField(null=True)
    upload_packet_sum = models.IntegerField(null=True)
    upload_bytes = models.IntegerField(null=True)
    upload_bytes_sum = models.IntegerField(null=True)
    upload_errors = models.IntegerField(null=True)
    upload_errors_sum = models.IntegerField(null=True)

    @classmethod
    def update(cls, xmldoc, server, service):
        net_name = get_value(service, "", "", "name")
        net, created = cls.objects.get_or_create(server=server, name=net_name)
        net.name = get_value(service, "", "", "name")
        net.status = decode_status(int(get_value(service, "status", "")))
        net.status_hint = get_string(service, "status_hint", "")
        net.monitor = get_string(service, "monitor", "")
        net.monitormode = get_string(service, "monitormode", "")
        net.pendingaction = get_string(service, "pendingaction", "")

        net.download_packet = get_int(service, "link.download.packets.now", None)
        net.download_packet_sum = get_int(service, "link.download.packets.total", None)
        net.download_bytes = get_int(service, "link.download.bytes.now", None)
        net.download_bytes_sum = get_int(service, "link.download.bytes.total", None)
        net.download_errors = get_int(service, "link.download.errors.total", None)
        net.download_errors_sum = get_int(service, "link.download.errors.total", None)

        net.upload_packet = get_int(service, "link.upload.packets.now", None)
        net.upload_packet_sum = get_int(service, "link.upload.packets.total", None)
        net.upload_bytes = get_int(service, "link.upload.bytes.now", None)
        net.upload_bytes_sum = get_int(service, "link.upload.bytes.total", None)
        net.upload_errors = get_int(service, "link.upload.errors.total", None)
        net.upload_errors_sum = get_int(service, "link.upload.errors.total", None)

        net.state = get_int(service, "state", None)
        net.duplex = get_int(service, "duplex", None)
        net.speed = get_int(service, "speed", None)

        net.save()

djangomonitcollector/datacollector/models/Platform.py
from django.db import models

from utils import get_value


class Platform(models.Model):
    server = models.OneToOneField('Server')
    name = models.TextField(null=True)
    release = models.TextField(null=True)
    version = models.TextField(null=True)
    machine = models.TextField(null=True)
    cpu = models.IntegerField(null=True)
    memory = models.IntegerField(null=True)
    swap = models.IntegerField(null=True)

    @classmethod
    def update(cls, xmldoc, server):
        platform, created = Platform.objects.get_or_create(server=server)
        platform.name = get_value(xmldoc, "platform", "name")
        platform.release = get_value(xmldoc, "platform", "release")
        platform.version = get_value(xmldoc, "platform", "version")
        platform.machine = get_value(xmldoc, "platform", "machine")
        platform.cpu = get_value(xmldoc, "platform", "cpu")
        platform.memory = get_value(xmldoc, "platform", "memory")
        platform.swap = get_value(xmldoc, "platform", "swap")
        platform.save()

djangomonitcollector/templates/datacollector/monitevent_filter.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load widget_tweaks %}
{% load pagination_tags %}
{% load bootstrap_pagination %}


{% load extra_tags %}
{% block title %} Events Dashboard {% endblock %}
{% block page_title %}Events Dashboard {% endblock %}
{% block css %}
<link href="{% static 'vendors/bower_components/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.css' %}" rel="stylesheet">
<style type="text/css" media="print">
   .no-print { display: none; }

</style>
<style type="text/css">
    .fade_me {
    filter: alpha(opacity=60);
    opacity: 0.60;
   }

   tr:hover {
    filter: alpha(opacity=100);
    opacity: 1;
   }
</style>

{% endblock %}

{% block submenu %}
  <li class="nav-item">
    <a class="nav-link" href="#"><i class="fa fa-arrows-v"></i>Timeline View </a>
    <a class="nav-link" href="#"><i class="fa fa-calendar"></i>Calendar View </a>
  </li>
  {% endblock submenu %}
{% block content %}
                {% autopaginate filter.qs 10 as filter_list %}

<div class="card">
    {% with request.path|urlencode|add:"_filter-details" as key %}

    <div class="card-header ch-alt ">
        <h2 style="{{key|get_card_header_opacity:user}}"> Filter details <small class="c-yellow m-t-5" id="filter-details">{{description}}</small></h2>
        <button class="btn btn-default btn-float waves-effect waves-circle waves-float {{theme}}" onclick="minimize(this,'{{request.path|urlencode}}','filter-details')" ><i class="zmdi {{key|get_card_button_style:user}}"></i></button>
    </div>
        <div class="card-body card-padding {{key|get_card_status:user}}" style="{{key|get_card_style:user}}">
    {% endwith %}


<form  action="" method="get" id="filter_form">
    <div class="row">
        <div class="form-group col-md-3">
            <label for="id_server">{% trans 'Server' %}:</label>
            {{ filter.form.server|add_class:"form-control input-sm chosen" }}
        </div>
        <div class="form-group col-md-3">
            <label for="id_service">{% trans 'Service' %}:</label>
            {{ filter.form.service|add_class:"form-control input-sm chosen" }}
        </div>
        <div class="form-group col-md-3">
            <label for="id_event_type">{% trans 'Event Type' %}:</label>
            {{ filter.form.event_type|add_class:"form-control input-sm chosen" }}
        </div>
        <div class="form-group col-md-3">
            <label for="id_event_id">{% trans 'Event ID' %}:</label>
            {{ filter.form.event_id|add_class:"form-control input-sm chosen" }}
        </div>
        <div class="form-group col-md-3">
            <label for="id_event_state">{% trans 'Event State' %}:</label>
            {{ filter.form.event_state|add_class:"form-control input-sm chosen" }}
        </div>
        <div class="form-group col-md-3 fg-line">
            <label for="id_event_message">{% trans 'Event Message' %}:</label>
            {{ filter.form.event_message|add_class:"form-control input-sm" }}
        </div>
        <div class="form-group col-md-3">
            <label for="id_alarm_raised">{% trans 'Raised ?' %}:</label>
            {{ filter.form.alarm_raised|add_class:"form-control input-sm chosen" }}
        </div>
        <div class="form-group col-md-3">
            <label for="id_is_ack">{% trans 'Is Acknowledged ?' %}:</label>
            {{ filter.form.is_ack|add_class:"form-control input-sm chosen" }}
        </div>
        <div class="form-group col-md-4">
            {{ filter.form.event_time.label_tag }}
            {{ filter.form.event_time|add_class:"form-control "|attr:'autocomplete:off' }}
        </div>
    </div>
    <div class="row">
        {% include "ui/includes/_widget_buttonbar.html" with caption="Disk Usage"  %}
        <button class="btn btn-primary" type="submit" >{% trans 'Filter' %}</button>
        <button class="btn bgm-indigo pull-right" type="button" onclick="reset_filter()">{% trans 'Reset Filter' %}</button>
        {% include "ui/includes/_end_widget.html" %}
    </div>
</form>
</div>
</div>
<div class="row text-center">
{% bootstrap_paginate page_obj range=10 show_prev_next="true" show_first_last="true" %}
</div>
<div class="box float-e-margins">
<div class="box-content">
<div class="table-responsive">
    <table class="table table-striped table-bordered table-hover fixed-header-table" id="event_table">
        <thead>
            <tr>
                <th></th>
                <th>Server</th>
                <th>Message</th>
                <th>Event</th>
                <th>Type</th>
                <th>Monit Action</th>
                <th>Raised</th>
                <th class="col-sm-1">Duplicate of</th>
                <th>cleared by</th>
                <th>cleared </th>
            </tr>
        </thead>
        <tbody>
            {% for monit_event in filter_list %}
                {% include "ui/includes/_event_row.html" %}
            {% empty %}
            <tr >
                <td colspan="10"><div class="alert alert-info"> {% trans " :)" %}</div></td>
            </tr>
        {% endfor %}

    </tbody>
    <tfoot>
    <tr>
        <th></th>
        <th>Server</th>
        <th>Message</th>
        <th>Event</th>
        <th>Type</th>
        <th>Monit Action</th>
        <th>Raised</th>
        <th>Duplicate of</th>
        <th>cleared by</th>
        <th>cleared </th>
    </tr>
    </tfoot>
</table>
</div>
<div class="row text-center">
{% bootstrap_paginate page_obj range=10 show_prev_next="true" show_first_last="true" %}
</div>
</div>
</div>
{% endblock %}
{% block javascript %}


    <script src="{% static 'vendors/bower_components/moment/min/moment.min.js' %}"></script>
    <script src="{% static 'vendors/bower_components/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js' %}"></script>
 <script type="text/javascript">

 function reset_filter(){
    window.location.href ="{% url 'ui:intellievent_2' %}"

 }

    $(document).ready(function() {


        if(window.localStorage) {
        localStorageSupport = true
        }

         if (localStorageSupport){
                localStorage.removeItem("notifications_count", 0);
                $('#notification_count').hide()
        }




        $('.collapse-link').click(function (){
            style = $("#filter_properties").css("display");
            // none = Displayed
            // block = Hidden (yes it's flipped)
            if (style== "none")
                localStorage.setItem("box-collapsed",'on');
            else
                localStorage.setItem("box-collapsed",'off');
        })

        if (localStorageSupport){
            box_status = localStorage.getItem("box-collapsed")
            if (box_status=="off"){
                $("#filter_properties").css("display", "none");
                $("#box_filter").addClass('border-bottom')
            }
        }





     function getParameterByName(name, url) {
        if (!url) url = window.location.href;
        name = name.replace(/[\[\]]/g, "\\$&");
        var regex = new RegExp("[?&]" + name + "(=([^&#]*)|&|#|$)", "i"),
            results = regex.exec(url);
        if (!results) return null;
        if (!results[2]) return '';
        return decodeURIComponent(results[2].replace(/\+/g, " "));
}

        var box_header = ""
        var event_type = getParameterByName('event_type'); // "lorem"
        var event_id = getParameterByName('event_id'); // "" (present with empty value)
        var event_state = getParameterByName('event_state'); // "" (present with no value)
        var event_message = getParameterByName('event_message'); // null (absent)
        var alarm_raised = getParameterByName('alarm_raised'); // null (absent)
        var is_ack = getParameterByName('is_ack'); // null (absent)
        var server = getParameterByName('server'); // null (absent)


        if(server){
            box_header += " | Server :  <b>"+ $('#id_server option:selected').html()+"</b>"
        }
        if(event_type){
            box_header += " | Event type :  <b>"+ $('#id_event_type option:selected').html()+"</b>"
        }
        if(event_id){
            box_header += " | Event ID :  <b>"+ $('#id_event_id option:selected').html()+"</b>"
        }
        if(event_state){
            box_header += " | Event State :  <b>"+ $('#id_event_state option:selected').html()+"</b>"
        }
        if(event_message){
            box_header += " | Event Message contains  <b>'"+ $('#id_event_message').val()+"'</b>"
        }
        if(alarm_raised){
            var val = $('#id_alarm_raised option:selected').html()
            if (val!="Unknown")
                box_header += " | Is Raised? : "+val
        }
        if(is_ack){
            var val = $('#id_is_ack option:selected').html()
            if (val!="Unknown")
                box_header += " | Is Acknowledged ? : <b>"+ $('#id_is_ack option:selected').html()+"</b>"
        }
        $('#filter-details').html(box_header)

        $('#id_event_time_0').datetimepicker();
        $('#id_event_time_1').datetimepicker({
            useCurrent: false //Important! See issue #1075
        });
        $("#id_event_time_0").on("dp.change", function (e) {
            $('#id_event_time_1').data("DateTimePicker").minDate(e.date);
        });
        $("#id_event_time_1").on("dp.change", function (e) {
            $('#id_event_time_0').data("DateTimePicker").maxDate(e.date);
        });

});

        </script>
    {% endblock javascript %}