api/urls.py
try:
    from django.conf.urls import *
except ImportError:  # django < 1.4
    from django.conf.urls.defaults import *

# place app url patterns here

from djangomonitcollector.users.models import User
from rest_framework import routers
from api.views import UserViewSet
from api import views


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^online-servers/$', views.OnlineServerList.as_view(), name="online-server-list"),
    url(r'^offline-servers/$', views.OfflineServerList.as_view(), name="offline-server-list"),
    url(r'^all-servers/$', views.ServerList.as_view(), name="server-list"),
    url(r'^server/(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$', views.ServerDetail.as_view(), name="server-detail"),
    url(r'^server/(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/alert$', views.ServerAlertList.as_view(), name="server-alert"),
    url(r'^alert/(?P<pk>[0-9]*)$', views.AlertDetail.as_view(), name="alert-detail"),
]

config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from django.views.generic.base import RedirectView
from rest_framework_swagger.views import get_swagger_view
from django.conf import settings  # import the settings file


favicon_view = RedirectView.as_view(
    url='/static/favicon/favicon.ico', permanent=True)
favicon_16_view = RedirectView.as_view(
    url='/static/favicon/favicon-16x16.png', permanent=True)
favicon_32_view = RedirectView.as_view(
    url='/static/favicon/favicon-32x32.png', permanent=True)
apple_touch_icon = RedirectView.as_view(
    url='/static/favicon/apple-touch-icon.png', permanent=True)
android_manifest = RedirectView.as_view(
    url='/static/favicon/manifest.json', permanent=True)
safari_pinned_tab = RedirectView.as_view(
    url='/static/favicon/safari-pinned-tab.svg', permanent=True)

app_name = settings.APPNAME
api_version = settings.APIVERSION


schema_view = get_swagger_view(
    title="{} API v{}".format(app_name, api_version))

urlpatterns = [


    # Restful API
    url(r'^v1/$', schema_view, name="kairos_api"),
    url(r'^v1/', include("api.urls")),

    # Favicons
    url(r'^favicon\.ico$', favicon_view),
    url(r'^favicon\-16x16\.png$', favicon_16_view),
    url(r'^favicon\-32x32\.png$', favicon_32_view),
    url(r'^apple\-touch\-icon\.png$', apple_touch_icon),
    url(r'^manifest\.json$', android_manifest),
    url(r'^safari\-pinned\-tab\.svg$', safari_pinned_tab),


    # Home
    url(r'^$', 'djangomonitcollector.ui.views.dashboard', name="home"),

    # About
    url(r'^about/$',
        TemplateView.as_view(template_name='pages/about.html'), name="about"),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/',
        include("djangomonitcollector.users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    # DataCollector
    url(r'^dc/', include("djangomonitcollector.datacollector.urls",
                         namespace="datacollector")),

    # UI
    url(r'^ui/', include("djangomonitcollector.ui.urls", namespace="ui")),

    # Notification
    url(r'^notification/',
        include("djangomonitcollector.notificationsystem.urls", namespace="n")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request),
        url(r'^403/$', default_views.permission_denied),
        url(r'^404/$', default_views.page_not_found),
        url(r'^500/$', default_views.server_error),
    ]

djangomonitcollector/datacollector/urls.py
from django.conf.urls import url

from djangomonitcollector.datacollector.views import OrganisationListView,\
    OrganisationCreateView,\
    OrganisationUpdateView,\
    collector,\
    list_servers,\
    delete_server

urlpatterns = [

    url(r'^organisations/$',
        OrganisationListView.as_view(),
        name='organisations'),

    url(r'^new_organisation/$',
        OrganisationCreateView.as_view(),
        name='new_organisation'),

    url(r'^update_organisation/(?P<pk>.+)/$',
        OrganisationUpdateView.as_view(),
        name='update_organisation'),

    url(r'^delete/([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        delete_server,
        name='delete_server'),
    url(
        r'^collector/(?P<collector_key>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        collector,
        name='collector'
    ),
    url(
        r'^collector/(?P<collector_key>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/(?P<host_group>.+)/$',
        collector,
        name='collector_with_host_group'
    ),
    url(
        r'^get_servers/$',
        list_servers,
        name='list_servers'
    ),
]

djangomonitcollector/notificationsystem/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^notificationtype/get_plugin_form/$',
        view=views.get_notification_plugin_form,
        name='get_plugin_form'
    ),
    url(
        regex=r'^notificationtype/create/$',
        view=views.NotificationTypeCreate.as_view(),
        name='notificationtype_create'
    ),
    url(
        regex=r'^notificationtype/show/(?P<pk>[0-9a-z]+)/$',
        view=views.NotificationTypeView.as_view(),
        name='notificationtype_view'
    ),
    url(
        regex=r'^notificationtype/mute/(?P<pk>[0-9a-z]+)/$',
        view=views.notificationtype_mute_all,
        name='notification_mute_all'
    ),
    url(
        regex=r'^notificationtype/update/(?P<pk>[0-9a-z]+)/$',
        view=views.NotificationTypeUpdate.as_view(),
        name='notificationtype_update'
    ),
    url(
        regex=r'^notificationtype/toggle/(?P<pk>[0-9a-z]+)/$',
        view=views.notificationtypeactivation,
        name='notificationtype_activation'
    ),
    url(
        regex=r'^notificationtype/delete/(?P<pk>[0-9a-z]+)/$',
        view=views.NotificationTypeDelete.as_view(),
        name='notificationtype_delete'
    ),
    url(
        regex=r'^notificationtype/list/$',
        view=views.NotificationTypeListView.as_view(),
        name='notificationtype_list'
    ),
    url(
        regex=r'^event/get_row/$',
        view=views.get_event_row,
        name='get_event_row'
    ),
    url(
        regex=r'^event/get/$',
        view=views.get_event_details,
        name='get_event_details'
    ),
    url(
        regex=r'^notification/get/$',
        view=views.get_notification_details,
        name='get_notification_details'
    ),
    url(
        regex=r'^postcomment/$',
        view=views.postcomment,
        name='postcomment'
    ),

]

djangomonitcollector/ui/urls.py
from . import views
from django.conf.urls import url


urlpatterns = [

    url(
        regex=r'^$',
        view=views.dashboard,
        name='dashboard'
    ),
    url(
        regex=r'^notifications/$',
        view=views.notifications,
        name='notifications'
    ),

    url(
        regex=r'^dashboard/$',
        view=views.dashboard,
        name='dashboard'
    ),
    url(
        regex=r'^server/update/(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        view=views.ServerUpdateView.as_view(),
        name='server_update'
    ),
    url(
        regex=r'^server/delete/(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        view=views.ServerDeleteView.as_view(),
        name='server_delete'
    ),
    url(
        regex=r'^server/show/(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        view=views.ServerShowView.as_view(),
        name='server_show'
    ),
    url(
        regex=r'^server/kpis/(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        view=views.serverkpis,
        name='server_kpis'
    ),
    url(
        regex=r'^server/(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/alerts/list/$',
        view=views.EventListView.as_view(),
        name='server_alerts'
    ),
    url(
        regex=r'^server/(?P<server_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        view=views.server,
        name='server'
    ),
    url(
        regex=r'^server/(?P<server_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/process/(?P<process_name>[^/]+)/$',
        view=views.process,
        name='process'
    ),
    url(
        regex=r'^server/(?P<server_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/filesystem/(?P<filesystem_id>[^/]+)/$',
        view=views.filesystem,
        name='filesystem'
    ),
    url(
        regex=r'^server/(?P<server_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/network/(?P<network_name>[^/]+)/$',
        view=views.network,
        name='network'
    ),
    url(
        regex=r'^confirm_delete/(?P<server_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        view=views.confirm_delete,
        name='confirm_delete'
    ),
    url(
        regex=r'^delete_server/(?P<server_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        view=views.delete_server,
        name='delete_server'
    ),
    url(
        regex=r'ackevent/$',
        view=views.ack_event,
        name='ack_event'
    ),
    url(
        regex=r'^load_dashboard_table/$',
        view=views.load_dashboard_table,
        name='load_dashboard_table'
    ),
    url(
        regex=r'settings/(?P<pk>.*)/$$',
        view=views.SettingsUpdateView.as_view(),
        name='settings_update'
    ),
    url(
        regex=r'intellievent/$',
        view=views.IntelliEvent.as_view(),
        name='intellievent'
    ),
    url(
        regex=r'intellievent2/$',
        view=views.intellievent_list,
        name='intellievent_2'
    ),
    url(
        regex=r'update_hgs/$',
        view=views.update_user_hgs,
        name='update_hgs'
    ),
    url(
        regex=r'set_stats_period/$',
        view=views.set_stats_period,
        name='set_stats_period'
    ),
    url(
        regex=r'last_week_events/$',
        view=views.get_weeks_events,
        name='last_week_events'
    ),
    url(
        regex=r'today_events/$',
        view=views._get_todays_events,
        name='today_events'
    ),

]

djangomonitcollector/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [

    url(
        regex=r'del_api_key/$',
        view=views.delete_api_key,
        name='delete_api_key'
    ),
    url(
        regex=r'new_api_key/$',
        view=views.new_api_key,
        name='new_api_key'
    ),
    url(
        regex=r'update_user_settings/$',
        view=views.update_user_settings,
        name='update_user_settings'
    ),
    url(
        r'^create/$',
        views.UserCreate.as_view(),
        name='create'
    ),
    url(
        regex=r'newck/$',
        view=views.new_collector_key,
        name='new_collector_key'
    ),
    url(
        regex=r'delck/$',
        view=views.delete_collector_key,
        name='delete_collector_key'
    ),

    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='index'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^update/(?P<pk>.+)/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),

    url(r'^delete/(?P<username>[\w.@+-]+)/$',
        views.UserDeleteView.as_view(), name='delete'),
    url(r'^update_password/(?P<pk>.+)/$',
        views.UpdatePasswordForUser, name='update_password'),
    url(r'^update_password/$', views.UpdatePassword,
        name='update_password_cu'),



]

djangomonitcollector/datacollector/models/File.py
from django.db import models

from service import Service
from utils import get_value, decode_status


class File(Service):
    server = models.ForeignKey('Server')

    @classmethod
    def update(cls, xmldoc, server, service):
        filename = get_value(service, "", "", "name")
        file, created = cls.objects.get_or_create(server=server, name=filename)
        file.name = filename
        file.status = decode_status(int(get_value(service, "status", "")))
        file.status_hint = get_value(service, "status_hint", "")
        file.monitor = get_value(service, "monitor", "")
        file.monitormode = get_value(service, "monitormode", "")
        file.pendingaction = get_value(service, "pendingaction", "")
        file.save()

djangomonitcollector/datacollector/models/FileSystem.py
from django.db import models

from service import Service
from utils import get_value, decode_status, json_list_append


class FileSystem(Service):
    server = models.ForeignKey('Server')
    date_last = models.PositiveIntegerField(null=True)
    file_system = models.TextField(null=True)
    mode = models.TextField(null=True)
    flags = models.IntegerField(null=True)

    blocks_percent = models.TextField(null=True)
    blocks_percent_last = models.FloatField(null=True)
    blocks_usage = models.TextField(null=True)
    blocks_usage_last = models.FloatField(null=True)
    blocks_total = models.TextField(null=True)

    inode_percent = models.TextField(null=True)
    inode_percent_last = models.FloatField(null=True)
    inode_usage = models.TextField(null=True)
    inode_usage_last = models.IntegerField(null=True)
    inode_total = models.TextField(null=True)

    @classmethod
    def update(cls, xmldoc, server, service):
        fs_name = get_value(service, "", "", "name")
        fs_name.replace('_', '')
        filesystem, created = cls.objects.get_or_create(server=server, name=fs_name)
        filesystem.name = fs_name
        filesystem.status = decode_status(int(get_value(service, "status", "")))
        filesystem.status_hint = get_value(service, "status_hint", "")
        filesystem.monitor = get_value(service, "monitor", "")
        filesystem.monitormode = get_value(service, "monitormode", "")
        filesystem.pendingaction = get_value(service, "pendingaction", "")

        # blocks
        percent_last = get_value(service, "block", "percent")
        if percent_last == "none":
            percent_last = "0.0"
        filesystem.blocks_percent_last = float(percent_last)
        filesystem.blocks_percent = json_list_append(filesystem.blocks_percent, filesystem.blocks_percent_last)

        # inode
        percent_last = get_value(service, "inode", "percent")
        if percent_last == "none":
            percent_last = "0.0"
        filesystem.inode_percent_last = float(percent_last)
        filesystem.inode_percent = json_list_append(filesystem.inode_percent, filesystem.inode_percent_last)

        filesystem.save()

djangomonitcollector/datacollector/models/Platform.py
from django.db import models

from utils import get_value


class Platform(models.Model):
    server = models.OneToOneField('Server')
    name = models.TextField(null=True)
    release = models.TextField(null=True)
    version = models.TextField(null=True)
    machine = models.TextField(null=True)
    cpu = models.IntegerField(null=True)
    memory = models.IntegerField(null=True)
    swap = models.IntegerField(null=True)

    @classmethod
    def update(cls, xmldoc, server):
        platform, created = Platform.objects.get_or_create(server=server)
        platform.name = get_value(xmldoc, "platform", "name")
        platform.release = get_value(xmldoc, "platform", "release")
        platform.version = get_value(xmldoc, "platform", "version")
        platform.machine = get_value(xmldoc, "platform", "machine")
        platform.cpu = get_value(xmldoc, "platform", "cpu")
        platform.memory = get_value(xmldoc, "platform", "memory")
        platform.swap = get_value(xmldoc, "platform", "swap")
        platform.save()

djangomonitcollector/datacollector/models/Service.py
from django.db import models


# Service
class Service(models.Model):
    # not unique since there could be multiple server with service 'nginx', etc.
    name = models.TextField()
    status = models.TextField(null=True)
    status_hint = models.IntegerField(null=True)
    monitor = models.IntegerField(null=True)
    monitor_mode = models.IntegerField(null=True)
    pending_action = models.IntegerField(null=True)

djangomonitcollector/templates/ui/includes/_dashboard_server_row.html
{% load  i18n %}
{% load extra_tags %}
<tr>
    <td id="{{server.id|clean}}_server_up"><span data-toggle="tooltip" data-placement="top" title="{% trans 'Server Status' %} : {{  server.server_up|server_status_to_string }}">{{ server.server_up|server_status_to_css_class|safe}}</span></td>
    <td>{{ server.localhostname }}</td>
    <td>{{ server.external_ip }}</td>
    <td>{{ server.monit_version }}</td>
    <td id="{{server.id|clean}}_uptime">{{ server.uptime|time_str }}</td>
    <td> <span class="label" id="{{server.id|clean}}_load_1">{{ server.system.load_avg01_last }} </span> <span class="label" id="{{server.id|clean}}_load_5"> {{ server.system.load_avg05_last }}</span> <span class="label" id="{{server.id|clean}}_load_15">{{ server.system.load_avg15_last }}</span></td>
    <td id="{{server.id|clean}}_cpu_progress_bar">{{ server.system.cpu_user_last|percent_to_bar|safe }}</td>
    <td id="{{server.id|clean}}_memory_progress_bar">{{  server.system.memory_percent_last|percent_to_bar|safe }}</td>
    <td id="{{server.id|clean}}_last_received_data"><span class="label {{ server.system.date_last|time_class }}">{{ server.system.date_last|timestamp_to_date }} </span></td>
    <td class="text-center"><a data-toggle="tooltip" data-placement="top" title="{% trans 'Server Alerts' %}"  href="{% url 'ui:server_alerts' server.id %}" ><span class="label {{ server.alerts|status_alert }}">{{server.alerts }}</span></a></td>
    <td class="text-center"><span data-toggle="tooltip" data-placement="top" title="{% trans 'Server Processes' %}" class="label label-success">{{server.processes }}</span></td>
    <td class="text-center">
        <a data-toggle="tooltip" data-placement="top" title="{% trans 'Settings' %}" class="btn btn-xs  bgm-indigo" href="{% url 'ui:server_show' server.id %}"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span></a>
        <a data-toggle="tooltip" data-placement="top" title="{% trans 'KPIs' %}" class="btn btn-xs  bgm-indigo" href="{% url 'ui:server_kpis' server.id %}"><span class="fa fa-bar-chart" aria-hidden="true"></span></a>
        <a data-toggle="tooltip" data-placement="top" title="{% trans 'View' %}" class="btn btn-xs  bgm-indigo" href="{% url 'ui:server' server.id %}"><span class="fa fa-eye" aria-hidden="true"></span></a>
        <a data-toggle="tooltip" data-placement="top" title="{% trans 'More Details' %}" data-href="{{server.id|clean}}_more_details" class="btn btn-xs btn btn-default hec-button waves-effect btn-toggle-info"><span class="fa fa-arrow-circle-down" aria-hidden="true"></span></a>
    </td>
</tr>
<tr id="{{server.id|clean}}_more_details">
    <td colspan="12"  class="p-0">
        <div class="col-md-12 server-data p-b-10" style="display:none">
            <div class="col-md-3 ">
                <h2 class="text-navy">{% trans 'System Properties' %}</h2>
                <span class="text-muted col-md-3">{% trans 'Name' %}:</span><span class="text-success"> {{ server.platform.name}}  </span>     <br/>
                <span class="text-muted col-md-3">{% trans 'Release' %}:</span><span class="text-success"> {{ server.platform.release}}</span> <br/>
                <span class="text-muted col-md-3">{% trans 'Version' %}:</span> <span class="text-success">{{ server.platform.version}} </span><br/>
                <span class="text-muted col-md-3">{% trans 'Machine' %}:</span><span class="text-success"> {{ server.platform.machine}}</span> <br/>
            </div>
            <div class="col-md-3">
                <h2 class="text-navy">{% trans 'CPU Usage' %}</h2>
                <span class="text-muted">CPU Cores:</span> <span class="text-success">{{ server.platform.cpu}}</span> <span class="text-muted">cores</span><br/>
                <span class="text-muted">CPU Wait:</span>
                <div id="{{server.id|clean}}_cpu_wait_progress_bar"></div>
                <span class="text-muted">CPU System:</span>
                <div id="{{server.id|clean}}_cpu_system_progress_bar"></div>
            </div>
            <div class="col-md-3">
                <h2 class="text-navy">{% trans 'Memory Usage' %}</h2>
                <span class="text-muted col-md-4">Total:</span><span class="text-success">  {{ server.platform.memory|kb_formatting|safe}}</span> <br/>
                <span class="text-muted col-md-4">Used:</span> <span id="{{server.id|clean}}_used_memory" class="text-success">{{ server.system.memory_kilobyte_last|kb_formatting|safe }} </span><br/>
                <span class="text-muted col-md-4">Swap:</span><span class="text-success"> {{ server.platform.swap|kb_formatting|safe}}</span>
            </div>
            <div class="col-md-3">
                <h2 class="text-navy">{% trans 'Disk Usage' %}</h2>
                <span class="text-muted col-md-4">Total:</span><span class="text-success" id="{{server.id|clean}}_disk_total"> N/A </span> <br/>
                <span class="text-muted col-md-4">Used:</span> <span id="{{server.id|clean}}_disk_used" class="text-success"> N/A </span><br/>
                <span class="text-muted col-md-4"></span><span class="col-md-10" id="{{server.id|clean}}_disk_used_percent" class="text-success"> N/A </span>
            </div>
        </td>
    </tr>
       <script language="javascript">

            var up_icon = '<span data-toggle="tooltip" data-placement="top" title="" data-original-title="Server Status : UP"><a href="#" class="btn btn-success btn-xs waves-effect"><span class="glyphicon glyphicon-upload"></span></a></span>'


            var socket = io('/{{ server.id|clean }}');
            socket.on('dmc', function(msg) {
                var data = msg.data;

                if (null != data.cpu_wait_last) {

                    $("#{{server.id|clean}}_memory_progress_bar").html(data.memory_last_progress_bar)
                    $("#{{server.id|clean}}_cpu_progress_bar").html(data.cpu_user_last_progress_bar)
                    $("#{{server.id|clean}}_uptime").html(data.uptime)

                    $("#{{server.id|clean}}_load_1").html(data.load_avg1_last)
                    $("#{{server.id|clean}}_load_5").html(data.load_avg5_last)
                    $("#{{server.id|clean}}_load_15").html(data.load_avg15_last)
                    $("#{{server.id|clean}}_used_memory").html(data.memory_last_kb_formatted)

                    $("#{{server.id|clean}}_cpu_wait_progress_bar").html(data.cpu_wait_last_progress_bar)
                    $("#{{server.id|clean}}_cpu_system_progress_bar").html(data.cpu_system_last_progress_bar)

                    $("#{{server.id|clean}}_server_up").html(up_icon)
                    $("#{{server.id|clean}}_last_received_data").html(data.last_received_data)

                }
                if (null != data.fs_blocks_percent_last) {
                        $("#{{server.id|clean}}_disk_total").html(data.fs_blocks_total_formatted)
                        $("#{{server.id|clean}}_disk_used").html(data.fs_blocks_usage_last_formatted)
                       // $("#{{server.id|clean}}_disk_used").html(data.fs_blocks_percent_last_formatted)
                        $("#{{server.id|clean}}_disk_used_percent").html(data.fs_blocks_percent_last_formatted)


                    }
                }
            );


        </script>

djangomonitcollector/templates/ui/includes/_end_widget.html
</div>
</div>
</div>

djangomonitcollector/templates/ui/includes/_event_row.html
{% load extra_tags %}
<tr id="event-{{ monit_event.id }}" class="{% if monit_event.alarm_raised and not monit_event.cleared_by %} c-red {% else %} fade_me {% endif %} {{monit_event.event_state|event_state_to_border_style}}">
<td class="text-center "><small><span class="label bgm-indigo" >{{ monit_event.id }}<span></small></td>
<td><a class="c-blue" target="_blank" href="{% url 'ui:server' monit_event.server.id %}" >{{ monit_event.server.localhostname }}</a></td>
<td>
    <div class="p-1">
        <span class="pull-right btn btn-xs c-lime" data-toggle="tooltip" data-placement="top" title="{{ monit_event.event_time}}"> {{ monit_event.event_time|time_diff|format_timedelta }}</span>
        <p class="m-b-xs">
            {{ monit_event.event_message }}
        </p>
        <div class="btn-group btn-group-xs" role="group">
            <button data-toggle="tooltip" data-placement="right" title="Comments" event-id="{{monit_event.id }}" type="button" class="btn btn-primary {{ monit_event.moniteventcomment_set.all|length|comments_style}} waves-effect view-event-comments "><i class="fa fa-comment-o"></i> <span>{{ monit_event.moniteventcomment_set.all|length}} </span> </button>
            <button data-toggle="tooltip" data-placement="top" title="Details" event-id="{{monit_event.id }}" type="button" class="btn btn-primary waves-effect view-event-details">View</button>
        </div>
    </div>
</td>
<td><b>{{ monit_event.event_id|event_status_to_string }}</b><br/><b><span class="label label-{{ monit_event.event_state|event_state_to_style }}">{{ monit_event.event_state|event_state_to_string }}</b></span></td>
<td>{{ monit_event.event_type|type_to_string }}<br/><strong>{{ monit_event.service}} </strong></td>
<td>{{ monit_event.event_action|action_to_string }}</td>
<td>{% if monit_event.event_state == 1  %} {{ monit_event.alarm_raised|to_icon|safe }} {% else %} - {% endif%}</td>
<td>{% if monit_event.event_state == 1  %} {{ monit_event.is_duplicate_of|to_btns|safe }} {% else %} - {% endif%}</td>
<td>{% if monit_event.event_state == 1 and monit_event.cleared_by  %} {{ monit_event.cleared_by|to_btn|safe }} {% else %} - {% endif%}</td>
<td>{% if monit_event.event_state == 0  %} {{ monit_event.cleared_alarms|to_btns|safe }} {% else %} - {% endif%}</td>
</tr>
<script type="text/javascript">
</script>

djangomonitcollector/templates/ui/includes/_widget.html
<div class="{{width}}">
<div class="card {{extra_classes}} " id="{{html_id}}">
    <div class="card-header ch-alt {{theme}} ">
        <h4 class="text-capitalize"  id="card_header"> {{ caption }} <small>{{description}}</small></h4>
    </div>

    <div class="card-body  card-padding">

djangomonitcollector/templates/ui/includes/_widget_buttonbar.html
<div class="card">
    <div class="card-body  card-padding">